### PR TITLE
Article Create Form

### PR DESCRIPTION
**Pull request by stevepop**
@JustSteveKing This PR is a request for assistance. I was unable to submit the Create Article form using Livewire. I am not sure where the problem is. When I submit the form, the request is not hitting the 'save' method on the `CreateArticle` component.

### CODE REVIEW

**Comment by JustSteveKing** [comment]
@stevepop I think LiveWire has issues with reactive model attributes. I would set the title and body as properties themselves and handle the model creation in the save method. I've had intermittent issues with things like `model.property` in livewire

**Comment by stevepop** [comment]
@JustSteveKing Thanks, let me try that 👍

**Comment by JustSteveKing** [comment]
No problems @stevepop buddy!

**Comment by stevepop** [comment]
@JustSteveKing, Hmm, probably something else. The form isn't submitting at all. I have changed the it to set the title and body attributes separately.

**Comment by JustSteveKing** [comment]
I will check the branch out tomorrow and have a look dude 🙂

**Comment by stevepop** [comment]
Thanks buddy, let me know if you find something I missed. I am new to Livewire so I am sure I missed something out. Have a good night my friend!

**Comment by stevepop** [comment]
This issue is now resolved closing this PR

**Pull request closed without merging**
